=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'date'

module SwaggerClient
  class V1AccessType
    WEB = 'ACCESS_TYPE_WEB'.freeze
    API = 'ACCESS_TYPE_API'.freeze
    ALL = 'ACCESS_TYPE_ALL'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = V1AccessType.constants.select { |c| V1AccessType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #V1AccessType" if constantValues.empty?
      value
    end
  end
end
