# -*- encoding: utf-8 -*-

=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

$:.push File.expand_path("../lib", __FILE__)
require "turnkey_client/version"

Gem::Specification.new do |s|
  s.name        = "turnkey_client"
  s.version     = TurnkeyClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Turnkey Engineering"]
  s.email       = ["hello@turnkey.com"]
  s.homepage    = "https://github.com/tkhq/ruby-sdk"
  s.summary     = "API Reference Ruby Gem"
  s.description = "HTTP client to interact with the Turnkey API"
  s.license     = 'Apache-2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'
  s.add_runtime_dependency 'openssl', '~> 3.2', '>= 3.0.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir.glob("{lib}/**/*") + %w[README.md Gemfile Rakefile turnkey_client.gemspec]
  s.executables   = []
  s.require_paths = ["lib"]
end
