=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::APIKeysApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'APIKeysApi' do
  before do
    # run before each test
    @instance = SwaggerClient::APIKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APIKeysApi' do
    it 'should create an instance of APIKeysApi' do
      expect(@instance).to be_instance_of(SwaggerClient::APIKeysApi)
    end
  end

  # unit tests for public_api_service_create_api_keys
  # Create API Keys
  # Add api keys to an existing User
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_create_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_delete_api_keys
  # Delete API Keys
  # Remove api keys from a User
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_delete_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_get_api_key
  # Get API key
  # Get details about an API key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1GetApiKeyResponse]
  describe 'public_api_service_get_api_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_get_api_keys
  # Get API key
  # Get details about API keys for a user
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1GetApiKeysResponse]
  describe 'public_api_service_get_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
