=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WalletsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WalletsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WalletsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WalletsApi' do
    it 'should create an instance of WalletsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WalletsApi)
    end
  end

  # unit tests for public_api_service_create_wallet
  # Create Wallet
  # Create a Wallet and derive addresses
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_create_wallet test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_create_wallet_accounts
  # Create Wallet Accounts
  # Derive additional addresses using an existing wallet
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_create_wallet_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_export_wallet
  # Export Wallet
  # Exports a Wallet
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_export_wallet test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_export_wallet_account
  # Export Wallet Account
  # Exports a Wallet Account
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1ActivityResponse]
  describe 'public_api_service_export_wallet_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_get_wallet
  # Get Wallet
  # Get details about a Wallet
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1GetWalletResponse]
  describe 'public_api_service_get_wallet test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_get_wallet_accounts
  # List Wallets Accounts
  # List all Accounts wirhin a Wallet
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1GetWalletAccountsResponse]
  describe 'public_api_service_get_wallet_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_api_service_get_wallets
  # List Wallets
  # List all Wallets within an Organization
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1GetWalletsResponse]
  describe 'public_api_service_get_wallets test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
