=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class ApiKeyCurve
    P256 = 'API_KEY_CURVE_P256'.freeze
    SECP256_K1 = 'API_KEY_CURVE_SECP256K1'.freeze
    ED25519 = 'API_KEY_CURVE_ED25519'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ApiKeyCurve.constants.select { |c| ApiKeyCurve::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ApiKeyCurve" if constantValues.empty?
      value
    end
  end
end
