=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class ClientSignatureScheme
    CLIENT_SIGNATURE_SCHEME_API_P256 = 'CLIENT_SIGNATURE_SCHEME_API_P256'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ClientSignatureScheme.constants.select { |c| ClientSignatureScheme::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ClientSignatureScheme" if constantValues.empty?
      value
    end
  end
end
