=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class CreateTvcDeploymentIntent
    # The unique identifier of the to-be-deployed TVC application
    attr_accessor :app_id

    # The QuorumOS version to use to deploy this application
    attr_accessor :qos_version

    # URL of the container containing the pivot binary
    attr_accessor :pivot_container_image_url

    # Location of the binary in the pivot container
    attr_accessor :pivot_path

    # Arguments to pass to the pivot binary at startup. Encoded as a list of strings, for example [\"--foo\", \"bar\"]
    attr_accessor :pivot_args

    # Digest of the pivot binary in the pivot container. This value will be inserted in the QOS manifest to ensure application integrity.
    attr_accessor :expected_pivot_digest

    # URL of the container containing the host binary
    attr_accessor :host_container_image_url

    # Location of the binary inside the host container
    attr_accessor :host_path

    # Arguments to pass to the host binary at startup. Encoded as a list of strings, for example [\"--foo\", \"bar\"]
    attr_accessor :host_args

    # Optional nonce to ensure uniqueness of the deployment manifest. If not provided, it defaults to the current Unix timestamp in seconds.
    attr_accessor :nonce

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_id' => :'appId',
        :'qos_version' => :'qosVersion',
        :'pivot_container_image_url' => :'pivotContainerImageUrl',
        :'pivot_path' => :'pivotPath',
        :'pivot_args' => :'pivotArgs',
        :'expected_pivot_digest' => :'expectedPivotDigest',
        :'host_container_image_url' => :'hostContainerImageUrl',
        :'host_path' => :'hostPath',
        :'host_args' => :'hostArgs',
        :'nonce' => :'nonce'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'app_id' => :'Object',
        :'qos_version' => :'Object',
        :'pivot_container_image_url' => :'Object',
        :'pivot_path' => :'Object',
        :'pivot_args' => :'Object',
        :'expected_pivot_digest' => :'Object',
        :'host_container_image_url' => :'Object',
        :'host_path' => :'Object',
        :'host_args' => :'Object',
        :'nonce' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'nonce'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::CreateTvcDeploymentIntent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::CreateTvcDeploymentIntent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'app_id')
        self.app_id = attributes[:'app_id']
      end

      if attributes.key?(:'qos_version')
        self.qos_version = attributes[:'qos_version']
      end

      if attributes.key?(:'pivot_container_image_url')
        self.pivot_container_image_url = attributes[:'pivot_container_image_url']
      end

      if attributes.key?(:'pivot_path')
        self.pivot_path = attributes[:'pivot_path']
      end

      if attributes.key?(:'pivot_args')
        if (value = attributes[:'pivot_args']).is_a?(Array)
          self.pivot_args = value
        end
      end

      if attributes.key?(:'expected_pivot_digest')
        self.expected_pivot_digest = attributes[:'expected_pivot_digest']
      end

      if attributes.key?(:'host_container_image_url')
        self.host_container_image_url = attributes[:'host_container_image_url']
      end

      if attributes.key?(:'host_path')
        self.host_path = attributes[:'host_path']
      end

      if attributes.key?(:'host_args')
        if (value = attributes[:'host_args']).is_a?(Array)
          self.host_args = value
        end
      end

      if attributes.key?(:'nonce')
        self.nonce = attributes[:'nonce']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @app_id.nil?
        invalid_properties.push('invalid value for "app_id", app_id cannot be nil.')
      end

      if @qos_version.nil?
        invalid_properties.push('invalid value for "qos_version", qos_version cannot be nil.')
      end

      if @pivot_container_image_url.nil?
        invalid_properties.push('invalid value for "pivot_container_image_url", pivot_container_image_url cannot be nil.')
      end

      if @pivot_path.nil?
        invalid_properties.push('invalid value for "pivot_path", pivot_path cannot be nil.')
      end

      if @pivot_args.nil?
        invalid_properties.push('invalid value for "pivot_args", pivot_args cannot be nil.')
      end

      if @expected_pivot_digest.nil?
        invalid_properties.push('invalid value for "expected_pivot_digest", expected_pivot_digest cannot be nil.')
      end

      if @host_container_image_url.nil?
        invalid_properties.push('invalid value for "host_container_image_url", host_container_image_url cannot be nil.')
      end

      if @host_path.nil?
        invalid_properties.push('invalid value for "host_path", host_path cannot be nil.')
      end

      if @host_args.nil?
        invalid_properties.push('invalid value for "host_args", host_args cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @app_id.nil?
      return false if @qos_version.nil?
      return false if @pivot_container_image_url.nil?
      return false if @pivot_path.nil?
      return false if @pivot_args.nil?
      return false if @expected_pivot_digest.nil?
      return false if @host_container_image_url.nil?
      return false if @host_path.nil?
      return false if @host_args.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_id == o.app_id &&
          qos_version == o.qos_version &&
          pivot_container_image_url == o.pivot_container_image_url &&
          pivot_path == o.pivot_path &&
          pivot_args == o.pivot_args &&
          expected_pivot_digest == o.expected_pivot_digest &&
          host_container_image_url == o.host_container_image_url &&
          host_path == o.host_path &&
          host_args == o.host_args &&
          nonce == o.nonce
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [app_id, qos_version, pivot_container_image_url, pivot_path, pivot_args, expected_pivot_digest, host_container_image_url, host_path, host_args, nonce].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
