=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class CredentialType
    WEBAUTHN_AUTHENTICATOR = 'CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR'.freeze
    API_KEY_P256 = 'CREDENTIAL_TYPE_API_KEY_P256'.freeze
    RECOVER_USER_KEY_P256 = 'CREDENTIAL_TYPE_RECOVER_USER_KEY_P256'.freeze
    API_KEY_SECP256_K1 = 'CREDENTIAL_TYPE_API_KEY_SECP256K1'.freeze
    EMAIL_AUTH_KEY_P256 = 'CREDENTIAL_TYPE_EMAIL_AUTH_KEY_P256'.freeze
    API_KEY_ED25519 = 'CREDENTIAL_TYPE_API_KEY_ED25519'.freeze
    OTP_AUTH_KEY_P256 = 'CREDENTIAL_TYPE_OTP_AUTH_KEY_P256'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CredentialType.constants.select { |c| CredentialType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CredentialType" if constantValues.empty?
      value
    end
  end
end
