=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class Curve
    SECP256_K1 = 'CURVE_SECP256K1'.freeze
    ED25519 = 'CURVE_ED25519'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Curve.constants.select { |c| Curve::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Curve" if constantValues.empty?
      value
    end
  end
end
