=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class DataV1SignatureScheme
    SIGNATURE_SCHEME_EPHEMERAL_KEY_P256 = 'SIGNATURE_SCHEME_EPHEMERAL_KEY_P256'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DataV1SignatureScheme.constants.select { |c| DataV1SignatureScheme::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DataV1SignatureScheme" if constantValues.empty?
      value
    end
  end
end
