=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class EthSendTransactionIntent
    # A wallet or private key address to sign with. This does not support private key IDs.
    attr_accessor :from

    # Whether to sponsor this transaction via Gas Station.
    attr_accessor :sponsor

    # CAIP-2 chain ID (e.g., 'eip155:1' for Ethereum mainnet).
    attr_accessor :caip2

    # Recipient address as a hex string with 0x prefix.
    attr_accessor :to

    # Amount of native asset to send in wei.
    attr_accessor :value

    # Hex-encoded call data for contract interactions.
    attr_accessor :data

    # Transaction nonce, for EIP-1559 and Turnkey Gas Station authorizations.
    attr_accessor :nonce

    # Maximum amount of gas to use for this transaction, for EIP-1559 transactions.
    attr_accessor :gas_limit

    # Maximum total fee per gas unit (base fee + priority fee) in wei. Required for non-sponsored (EIP-1559) transactions. Not used for sponsored transactions.
    attr_accessor :max_fee_per_gas

    # Maximum priority fee (tip) per gas unit in wei. Required for non-sponsored (EIP-1559) transactions. Not used for sponsored transactions.
    attr_accessor :max_priority_fee_per_gas

    # The gas station delegate contract nonce. Only used when sponsor=true. Include this if you want maximal security posture.
    attr_accessor :gas_station_nonce

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'from' => :'from',
        :'sponsor' => :'sponsor',
        :'caip2' => :'caip2',
        :'to' => :'to',
        :'value' => :'value',
        :'data' => :'data',
        :'nonce' => :'nonce',
        :'gas_limit' => :'gasLimit',
        :'max_fee_per_gas' => :'maxFeePerGas',
        :'max_priority_fee_per_gas' => :'maxPriorityFeePerGas',
        :'gas_station_nonce' => :'gasStationNonce'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'from' => :'Object',
        :'sponsor' => :'Object',
        :'caip2' => :'Object',
        :'to' => :'Object',
        :'value' => :'Object',
        :'data' => :'Object',
        :'nonce' => :'Object',
        :'gas_limit' => :'Object',
        :'max_fee_per_gas' => :'Object',
        :'max_priority_fee_per_gas' => :'Object',
        :'gas_station_nonce' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'sponsor',
        :'value',
        :'data',
        :'nonce',
        :'gas_limit',
        :'max_fee_per_gas',
        :'max_priority_fee_per_gas',
        :'gas_station_nonce'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::EthSendTransactionIntent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::EthSendTransactionIntent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      end

      if attributes.key?(:'sponsor')
        self.sponsor = attributes[:'sponsor']
      end

      if attributes.key?(:'caip2')
        self.caip2 = attributes[:'caip2']
      end

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end

      if attributes.key?(:'data')
        self.data = attributes[:'data']
      end

      if attributes.key?(:'nonce')
        self.nonce = attributes[:'nonce']
      end

      if attributes.key?(:'gas_limit')
        self.gas_limit = attributes[:'gas_limit']
      end

      if attributes.key?(:'max_fee_per_gas')
        self.max_fee_per_gas = attributes[:'max_fee_per_gas']
      end

      if attributes.key?(:'max_priority_fee_per_gas')
        self.max_priority_fee_per_gas = attributes[:'max_priority_fee_per_gas']
      end

      if attributes.key?(:'gas_station_nonce')
        self.gas_station_nonce = attributes[:'gas_station_nonce']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @caip2.nil?
        invalid_properties.push('invalid value for "caip2", caip2 cannot be nil.')
      end

      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @from.nil?
      return false if @caip2.nil?
      caip2_validator = EnumAttributeValidator.new('Object', ['eip155:1', 'eip155:11155111', 'eip155:8453', 'eip155:84532', 'eip155:137', 'eip155:80002'])
      return false unless caip2_validator.valid?(@caip2)
      return false if @to.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] caip2 Object to be assigned
    def caip2=(caip2)
      validator = EnumAttributeValidator.new('Object', ['eip155:1', 'eip155:11155111', 'eip155:8453', 'eip155:84532', 'eip155:137', 'eip155:80002'])
      unless validator.valid?(caip2)
        fail ArgumentError, "invalid value for \"caip2\", must be one of #{validator.allowable_values}."
      end
      @caip2 = caip2
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          from == o.from &&
          sponsor == o.sponsor &&
          caip2 == o.caip2 &&
          to == o.to &&
          value == o.value &&
          data == o.data &&
          nonce == o.nonce &&
          gas_limit == o.gas_limit &&
          max_fee_per_gas == o.max_fee_per_gas &&
          max_priority_fee_per_gas == o.max_priority_fee_per_gas &&
          gas_station_nonce == o.gas_station_nonce
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [from, sponsor, caip2, to, value, data, nonce, gas_limit, max_fee_per_gas, max_priority_fee_per_gas, gas_station_nonce].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
