=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class FiatOnRampProvider
    COINBASE = 'FIAT_ON_RAMP_PROVIDER_COINBASE'.freeze
    MOONPAY = 'FIAT_ON_RAMP_PROVIDER_MOONPAY'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = FiatOnRampProvider.constants.select { |c| FiatOnRampProvider::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #FiatOnRampProvider" if constantValues.empty?
      value
    end
  end
end
