=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class Outcome
    ALLOW = 'OUTCOME_ALLOW'.freeze
    DENY_EXPLICIT = 'OUTCOME_DENY_EXPLICIT'.freeze
    DENY_IMPLICIT = 'OUTCOME_DENY_IMPLICIT'.freeze
    REQUIRES_CONSENSUS = 'OUTCOME_REQUIRES_CONSENSUS'.freeze
    REJECTED = 'OUTCOME_REJECTED'.freeze
    ERROR = 'OUTCOME_ERROR'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Outcome.constants.select { |c| Outcome::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Outcome" if constantValues.empty?
      value
    end
  end
end
