=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class TvcDeployment
    # Unique Identifier for this TVC Deployment.
    attr_accessor :id

    # Unique Identifier of the Organization for this TVC Deployment
    attr_accessor :organization_id

    # Unique Identifier of the TVC App for this deployment
    attr_accessor :app_id

    attr_accessor :manifest_set

    attr_accessor :share_set

    attr_accessor :manifest

    # List of operator approvals for this manifest
    attr_accessor :manifest_approvals

    # QOS Version used for this deployment
    attr_accessor :qos_version

    attr_accessor :pivot_container

    attr_accessor :created_at

    attr_accessor :updated_at

    # Whether or not the user wants this deployment deleted from the cluster.
    attr_accessor :delete

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'organization_id' => :'organizationId',
        :'app_id' => :'appId',
        :'manifest_set' => :'manifestSet',
        :'share_set' => :'shareSet',
        :'manifest' => :'manifest',
        :'manifest_approvals' => :'manifestApprovals',
        :'qos_version' => :'qosVersion',
        :'pivot_container' => :'pivotContainer',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'delete' => :'delete'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'organization_id' => :'Object',
        :'app_id' => :'Object',
        :'manifest_set' => :'Object',
        :'share_set' => :'Object',
        :'manifest' => :'Object',
        :'manifest_approvals' => :'Object',
        :'qos_version' => :'Object',
        :'pivot_container' => :'Object',
        :'created_at' => :'Object',
        :'updated_at' => :'Object',
        :'delete' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::TvcDeployment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::TvcDeployment`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      end

      if attributes.key?(:'app_id')
        self.app_id = attributes[:'app_id']
      end

      if attributes.key?(:'manifest_set')
        self.manifest_set = attributes[:'manifest_set']
      end

      if attributes.key?(:'share_set')
        self.share_set = attributes[:'share_set']
      end

      if attributes.key?(:'manifest')
        self.manifest = attributes[:'manifest']
      end

      if attributes.key?(:'manifest_approvals')
        if (value = attributes[:'manifest_approvals']).is_a?(Array)
          self.manifest_approvals = value
        end
      end

      if attributes.key?(:'qos_version')
        self.qos_version = attributes[:'qos_version']
      end

      if attributes.key?(:'pivot_container')
        self.pivot_container = attributes[:'pivot_container']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'delete')
        self.delete = attributes[:'delete']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @organization_id.nil?
        invalid_properties.push('invalid value for "organization_id", organization_id cannot be nil.')
      end

      if @app_id.nil?
        invalid_properties.push('invalid value for "app_id", app_id cannot be nil.')
      end

      if @manifest_set.nil?
        invalid_properties.push('invalid value for "manifest_set", manifest_set cannot be nil.')
      end

      if @share_set.nil?
        invalid_properties.push('invalid value for "share_set", share_set cannot be nil.')
      end

      if @manifest.nil?
        invalid_properties.push('invalid value for "manifest", manifest cannot be nil.')
      end

      if @manifest_approvals.nil?
        invalid_properties.push('invalid value for "manifest_approvals", manifest_approvals cannot be nil.')
      end

      if @qos_version.nil?
        invalid_properties.push('invalid value for "qos_version", qos_version cannot be nil.')
      end

      if @pivot_container.nil?
        invalid_properties.push('invalid value for "pivot_container", pivot_container cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @delete.nil?
        invalid_properties.push('invalid value for "delete", delete cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @organization_id.nil?
      return false if @app_id.nil?
      return false if @manifest_set.nil?
      return false if @share_set.nil?
      return false if @manifest.nil?
      return false if @manifest_approvals.nil?
      return false if @qos_version.nil?
      return false if @pivot_container.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @delete.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          organization_id == o.organization_id &&
          app_id == o.app_id &&
          manifest_set == o.manifest_set &&
          share_set == o.share_set &&
          manifest == o.manifest &&
          manifest_approvals == o.manifest_approvals &&
          qos_version == o.qos_version &&
          pivot_container == o.pivot_container &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          delete == o.delete
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, organization_id, app_id, manifest_set, share_set, manifest, manifest_approvals, qos_version, pivot_container, created_at, updated_at, delete].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
