=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class TvcContainerSpec
    # The URL for this container image.
    attr_accessor :container_url

    # The path (in-container) to the executable binary.
    attr_accessor :path

    # The arguments to pass to the executable.
    attr_accessor :args

    # Whether or not this container requires a pull secret to access.
    attr_accessor :has_pull_secret

    attr_accessor :health_check_type

    # The port to use for health checks against this executable.
    attr_accessor :health_check_port

    # The port to use for public ingress to this executable.
    attr_accessor :public_ingress_port

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'container_url' => :'containerUrl',
        :'path' => :'path',
        :'args' => :'args',
        :'has_pull_secret' => :'hasPullSecret',
        :'health_check_type' => :'healthCheckType',
        :'health_check_port' => :'healthCheckPort',
        :'public_ingress_port' => :'publicIngressPort'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'container_url' => :'Object',
        :'path' => :'Object',
        :'args' => :'Object',
        :'has_pull_secret' => :'Object',
        :'health_check_type' => :'Object',
        :'health_check_port' => :'Object',
        :'public_ingress_port' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::TvcContainerSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::TvcContainerSpec`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'container_url')
        self.container_url = attributes[:'container_url']
      end

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      end

      if attributes.key?(:'args')
        if (value = attributes[:'args']).is_a?(Array)
          self.args = value
        end
      end

      if attributes.key?(:'has_pull_secret')
        self.has_pull_secret = attributes[:'has_pull_secret']
      end

      if attributes.key?(:'health_check_type')
        self.health_check_type = attributes[:'health_check_type']
      end

      if attributes.key?(:'health_check_port')
        self.health_check_port = attributes[:'health_check_port']
      end

      if attributes.key?(:'public_ingress_port')
        self.public_ingress_port = attributes[:'public_ingress_port']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @container_url.nil?
        invalid_properties.push('invalid value for "container_url", container_url cannot be nil.')
      end

      if @path.nil?
        invalid_properties.push('invalid value for "path", path cannot be nil.')
      end

      if @args.nil?
        invalid_properties.push('invalid value for "args", args cannot be nil.')
      end

      if @has_pull_secret.nil?
        invalid_properties.push('invalid value for "has_pull_secret", has_pull_secret cannot be nil.')
      end

      if @health_check_type.nil?
        invalid_properties.push('invalid value for "health_check_type", health_check_type cannot be nil.')
      end

      if @health_check_port.nil?
        invalid_properties.push('invalid value for "health_check_port", health_check_port cannot be nil.')
      end

      if @public_ingress_port.nil?
        invalid_properties.push('invalid value for "public_ingress_port", public_ingress_port cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @container_url.nil?
      return false if @path.nil?
      return false if @args.nil?
      return false if @has_pull_secret.nil?
      return false if @health_check_type.nil?
      return false if @health_check_port.nil?
      return false if @public_ingress_port.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          container_url == o.container_url &&
          path == o.path &&
          args == o.args &&
          has_pull_secret == o.has_pull_secret &&
          health_check_type == o.health_check_type &&
          health_check_port == o.health_check_port &&
          public_ingress_port == o.public_ingress_port
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [container_url, path, args, has_pull_secret, health_check_type, health_check_port, public_ingress_port].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
