=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class UpdateAuthProxyConfigIntent
    # Updated list of allowed origins for CORS.
    attr_accessor :allowed_origins

    # Updated list of allowed proxy authentication methods.
    attr_accessor :allowed_auth_methods

    # Custom 'from' address for auth-related emails.
    attr_accessor :send_from_email_address

    # Custom reply-to address for auth-related emails.
    attr_accessor :reply_to_email_address

    # Template ID for email-auth messages.
    attr_accessor :email_auth_template_id

    # Template ID for OTP SMS messages.
    attr_accessor :otp_template_id

    attr_accessor :email_customization_params

    attr_accessor :sms_customization_params

    attr_accessor :wallet_kit_settings

    # OTP code lifetime in seconds.
    attr_accessor :otp_expiration_seconds

    # Verification-token lifetime in seconds.
    attr_accessor :verification_token_expiration_seconds

    # Session lifetime in seconds.
    attr_accessor :session_expiration_seconds

    # Enable alphanumeric OTP codes.
    attr_accessor :otp_alphanumeric

    # Desired OTP code length (6–9).
    attr_accessor :otp_length

    # Custom 'from' email sender for auth-related emails.
    attr_accessor :send_from_email_sender_name

    # Verification token required for get account with PII (email/phone number). Default false.
    attr_accessor :verification_token_required_for_get_account_pii

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'allowed_origins' => :'allowedOrigins',
        :'allowed_auth_methods' => :'allowedAuthMethods',
        :'send_from_email_address' => :'sendFromEmailAddress',
        :'reply_to_email_address' => :'replyToEmailAddress',
        :'email_auth_template_id' => :'emailAuthTemplateId',
        :'otp_template_id' => :'otpTemplateId',
        :'email_customization_params' => :'emailCustomizationParams',
        :'sms_customization_params' => :'smsCustomizationParams',
        :'wallet_kit_settings' => :'walletKitSettings',
        :'otp_expiration_seconds' => :'otpExpirationSeconds',
        :'verification_token_expiration_seconds' => :'verificationTokenExpirationSeconds',
        :'session_expiration_seconds' => :'sessionExpirationSeconds',
        :'otp_alphanumeric' => :'otpAlphanumeric',
        :'otp_length' => :'otpLength',
        :'send_from_email_sender_name' => :'sendFromEmailSenderName',
        :'verification_token_required_for_get_account_pii' => :'verificationTokenRequiredForGetAccountPii'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'allowed_origins' => :'Object',
        :'allowed_auth_methods' => :'Object',
        :'send_from_email_address' => :'Object',
        :'reply_to_email_address' => :'Object',
        :'email_auth_template_id' => :'Object',
        :'otp_template_id' => :'Object',
        :'email_customization_params' => :'Object',
        :'sms_customization_params' => :'Object',
        :'wallet_kit_settings' => :'Object',
        :'otp_expiration_seconds' => :'Object',
        :'verification_token_expiration_seconds' => :'Object',
        :'session_expiration_seconds' => :'Object',
        :'otp_alphanumeric' => :'Object',
        :'otp_length' => :'Object',
        :'send_from_email_sender_name' => :'Object',
        :'verification_token_required_for_get_account_pii' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'send_from_email_address',
        :'reply_to_email_address',
        :'email_auth_template_id',
        :'otp_template_id',
        :'otp_expiration_seconds',
        :'verification_token_expiration_seconds',
        :'session_expiration_seconds',
        :'otp_alphanumeric',
        :'otp_length',
        :'send_from_email_sender_name',
        :'verification_token_required_for_get_account_pii'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::UpdateAuthProxyConfigIntent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::UpdateAuthProxyConfigIntent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'allowed_origins')
        if (value = attributes[:'allowed_origins']).is_a?(Array)
          self.allowed_origins = value
        end
      end

      if attributes.key?(:'allowed_auth_methods')
        if (value = attributes[:'allowed_auth_methods']).is_a?(Array)
          self.allowed_auth_methods = value
        end
      end

      if attributes.key?(:'send_from_email_address')
        self.send_from_email_address = attributes[:'send_from_email_address']
      end

      if attributes.key?(:'reply_to_email_address')
        self.reply_to_email_address = attributes[:'reply_to_email_address']
      end

      if attributes.key?(:'email_auth_template_id')
        self.email_auth_template_id = attributes[:'email_auth_template_id']
      end

      if attributes.key?(:'otp_template_id')
        self.otp_template_id = attributes[:'otp_template_id']
      end

      if attributes.key?(:'email_customization_params')
        self.email_customization_params = attributes[:'email_customization_params']
      end

      if attributes.key?(:'sms_customization_params')
        self.sms_customization_params = attributes[:'sms_customization_params']
      end

      if attributes.key?(:'wallet_kit_settings')
        self.wallet_kit_settings = attributes[:'wallet_kit_settings']
      end

      if attributes.key?(:'otp_expiration_seconds')
        self.otp_expiration_seconds = attributes[:'otp_expiration_seconds']
      end

      if attributes.key?(:'verification_token_expiration_seconds')
        self.verification_token_expiration_seconds = attributes[:'verification_token_expiration_seconds']
      end

      if attributes.key?(:'session_expiration_seconds')
        self.session_expiration_seconds = attributes[:'session_expiration_seconds']
      end

      if attributes.key?(:'otp_alphanumeric')
        self.otp_alphanumeric = attributes[:'otp_alphanumeric']
      end

      if attributes.key?(:'otp_length')
        self.otp_length = attributes[:'otp_length']
      end

      if attributes.key?(:'send_from_email_sender_name')
        self.send_from_email_sender_name = attributes[:'send_from_email_sender_name']
      end

      if attributes.key?(:'verification_token_required_for_get_account_pii')
        self.verification_token_required_for_get_account_pii = attributes[:'verification_token_required_for_get_account_pii']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          allowed_origins == o.allowed_origins &&
          allowed_auth_methods == o.allowed_auth_methods &&
          send_from_email_address == o.send_from_email_address &&
          reply_to_email_address == o.reply_to_email_address &&
          email_auth_template_id == o.email_auth_template_id &&
          otp_template_id == o.otp_template_id &&
          email_customization_params == o.email_customization_params &&
          sms_customization_params == o.sms_customization_params &&
          wallet_kit_settings == o.wallet_kit_settings &&
          otp_expiration_seconds == o.otp_expiration_seconds &&
          verification_token_expiration_seconds == o.verification_token_expiration_seconds &&
          session_expiration_seconds == o.session_expiration_seconds &&
          otp_alphanumeric == o.otp_alphanumeric &&
          otp_length == o.otp_length &&
          send_from_email_sender_name == o.send_from_email_sender_name &&
          verification_token_required_for_get_account_pii == o.verification_token_required_for_get_account_pii
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [allowed_origins, allowed_auth_methods, send_from_email_address, reply_to_email_address, email_auth_template_id, otp_template_id, email_customization_params, sms_customization_params, wallet_kit_settings, otp_expiration_seconds, verification_token_expiration_seconds, session_expiration_seconds, otp_alphanumeric, otp_length, send_from_email_sender_name, verification_token_required_for_get_account_pii].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
