=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class UpdateFiatOnRampCredentialIntent
    # The ID of the fiat on-ramp credential to update
    attr_accessor :fiat_onramp_credential_id

    attr_accessor :onramp_provider

    # Project ID for the on-ramp provider. Some providers, like Coinbase, require this additional identifier.
    attr_accessor :project_id

    # Publishable API key for the on-ramp provider
    attr_accessor :publishable_api_key

    # Secret API key for the on-ramp provider encrypted to our on-ramp encryption public key
    attr_accessor :encrypted_secret_api_key

    # Private API key for the on-ramp provider encrypted to our on-ramp encryption public key. Some providers, like Coinbase, require this additional key.
    attr_accessor :encrypted_private_api_key

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fiat_onramp_credential_id' => :'fiatOnrampCredentialId',
        :'onramp_provider' => :'onrampProvider',
        :'project_id' => :'projectId',
        :'publishable_api_key' => :'publishableApiKey',
        :'encrypted_secret_api_key' => :'encryptedSecretApiKey',
        :'encrypted_private_api_key' => :'encryptedPrivateApiKey'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'fiat_onramp_credential_id' => :'Object',
        :'onramp_provider' => :'Object',
        :'project_id' => :'Object',
        :'publishable_api_key' => :'Object',
        :'encrypted_secret_api_key' => :'Object',
        :'encrypted_private_api_key' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'project_id',
        :'encrypted_private_api_key'
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TurnkeyClient::UpdateFiatOnRampCredentialIntent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TurnkeyClient::UpdateFiatOnRampCredentialIntent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'fiat_onramp_credential_id')
        self.fiat_onramp_credential_id = attributes[:'fiat_onramp_credential_id']
      end

      if attributes.key?(:'onramp_provider')
        self.onramp_provider = attributes[:'onramp_provider']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'publishable_api_key')
        self.publishable_api_key = attributes[:'publishable_api_key']
      end

      if attributes.key?(:'encrypted_secret_api_key')
        self.encrypted_secret_api_key = attributes[:'encrypted_secret_api_key']
      end

      if attributes.key?(:'encrypted_private_api_key')
        self.encrypted_private_api_key = attributes[:'encrypted_private_api_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @fiat_onramp_credential_id.nil?
        invalid_properties.push('invalid value for "fiat_onramp_credential_id", fiat_onramp_credential_id cannot be nil.')
      end

      if @onramp_provider.nil?
        invalid_properties.push('invalid value for "onramp_provider", onramp_provider cannot be nil.')
      end

      if @publishable_api_key.nil?
        invalid_properties.push('invalid value for "publishable_api_key", publishable_api_key cannot be nil.')
      end

      if @encrypted_secret_api_key.nil?
        invalid_properties.push('invalid value for "encrypted_secret_api_key", encrypted_secret_api_key cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @fiat_onramp_credential_id.nil?
      return false if @onramp_provider.nil?
      return false if @publishable_api_key.nil?
      return false if @encrypted_secret_api_key.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fiat_onramp_credential_id == o.fiat_onramp_credential_id &&
          onramp_provider == o.onramp_provider &&
          project_id == o.project_id &&
          publishable_api_key == o.publishable_api_key &&
          encrypted_secret_api_key == o.encrypted_secret_api_key &&
          encrypted_private_api_key == o.encrypted_private_api_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [fiat_onramp_credential_id, onramp_provider, project_id, publishable_api_key, encrypted_secret_api_key, encrypted_private_api_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TurnkeyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
