=begin
#API Reference

#Review our [API Introduction](../api-introduction) to get started.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
=end

require 'date'

module TurnkeyClient
  class UsageType
    SIGNUP = 'USAGE_TYPE_SIGNUP'.freeze
    LOGIN = 'USAGE_TYPE_LOGIN'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = UsageType.constants.select { |c| UsageType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #UsageType" if constantValues.empty?
      value
    end
  end
end
